import {
  chromecast,
  disc02,
  discord,
  discordBlack,
  facebook,
  figma,
  file02,
  framer,
  homeSmile,
  instagram,
  notification2,
  notification3,
  notification4,
  notion,
  photoshop,
  plusSquare,
  protopie,
  raindrop,
  recording01,
  recording03,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  slack,
  sliders04,
  telegram,
  twitter,
  yourlogo,
} from '../assets';

export const navigation = [
  {
    id: '0',
    title: 'Reasearch Profile',
    url: 'reasearch-profile',
  },
  {
    id: '1',
    title: 'Journal Ranking',
    url: 'journal-ranking',
  },
  {
    id: '2',
    title: 'Reasearch Roadmap',
    url: 'research-roadmap',
  },
  {
    id: '3',
    title: 'Wanna Be a Researcher?',
    url: 'paper-writing',
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [yourlogo, yourlogo, yourlogo, yourlogo, yourlogo];

export const brainwaveServices = [
  'Photo generating',
  'Photo enhance',
  'Seamless Integration',
];

export const brainwaveServicesIcons = [
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
];

export const roadmap = [
  {
    id: '0',
    title: 'Voice recognition',
    text: 'Enable the chatbot to understand and respond to voice commands, making it easier for users to interact with the app hands-free.',
    date: 'May 2023',
    status: 'done',
    imageUrl: roadmap1,
    colorful: true,
  },
  {
    id: '1',
    title: 'Gamification',
    text: 'Add game-like elements, such as badges or leaderboards, to incentivize users to engage with the chatbot more frequently.',
    date: 'May 2023',
    status: 'progress',
    imageUrl: roadmap2,
  },
  {
    id: '2',
    title: 'Chatbot customization',
    text: "Allow users to customize the chatbot's appearance and behavior, making it more engaging and fun to interact with.",
    date: 'May 2023',
    status: 'done',
    imageUrl: roadmap3,
  },
  {
    id: '3',
    title: 'Integration with APIs',
    text: 'Allow the chatbot to access external data sources, such as weather APIs or news APIs, to provide more relevant recommendations.',
    date: 'May 2023',
    status: 'progress',
    imageUrl: roadmap4,
  },
];

export const collabText =
  "With smart automation and top-notch security, it's the perfect solution for teams looking to work smarter.";

export const collabContent = [
  {
    id: '0',
    title: 'Seamless Integration',
    text: collabText,
  },
  {
    id: '1',
    title: 'Smart Automation',
  },
  {
    id: '2',
    title: 'Top-notch Security',
  },
];

export const collabApps = [
  {
    id: '0',
    title: 'Figma',
    icon: figma,
    width: 26,
    height: 36,
  },
  {
    id: '1',
    title: 'Notion',
    icon: notion,
    width: 34,
    height: 36,
  },
  {
    id: '2',
    title: 'Discord',
    icon: discord,
    width: 36,
    height: 28,
  },
  {
    id: '3',
    title: 'Slack',
    icon: slack,
    width: 34,
    height: 35,
  },
  {
    id: '4',
    title: 'Photoshop',
    icon: photoshop,
    width: 34,
    height: 34,
  },
  {
    id: '5',
    title: 'Protopie',
    icon: protopie,
    width: 34,
    height: 34,
  },
  {
    id: '6',
    title: 'Framer',
    icon: framer,
    width: 26,
    height: 34,
  },
  {
    id: '7',
    title: 'Raindrop',
    icon: raindrop,
    width: 38,
    height: 32,
  },
];

export const pricing = [
  {
    id: '0',
    title: 'Basic',
    description: 'AI chatbot, personalized recommendations',
    price: '0',
    features: [
      'An AI chatbot that can understand your queries',
      'Personalized recommendations based on your preferences',
      'Ability to explore the app and its features without any cost',
    ],
  },
  {
    id: '1',
    title: 'Premium',
    description: 'Advanced AI chatbot, priority support, analytics dashboard',
    price: '9.99',
    features: [
      'An advanced AI chatbot that can understand complex queries',
      'An analytics dashboard to track your conversations',
      'Priority support to solve issues quickly',
    ],
  },
  {
    id: '2',
    title: 'Enterprise',
    description: 'Custom AI chatbot, advanced analytics, dedicated account',
    price: null,
    features: [
      'An AI chatbot that can understand your queries',
      'Personalized recommendations based on your preferences',
      'Ability to explore the app and its features without any cost',
    ],
  },
];

export const benefitData = [
  {
    profile: 'https://www.adscientificindex.com/scientist/rashidul-haque/12345',
    name: 'Rashidul Haque',
    institution: 'International Centre for Diarrhoeal Disease Research, Dhaka',
    country: 'Bangladesh',
    field: 'Parasitic Diseases',
    institutional_ranking: '1',
    country_ranking: '1',
    regional_ranking: '11,180',
    world_ranking: '11,180',
    hIndexTotal: '95',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '417',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '35,025',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/firdausi-qadri/67890',
    name: 'Firdausi Qadri',
    institution: 'International Centre for Diarrhoeal Disease Research, Dhaka',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Immunology',
    institutional_ranking: '2',
    country_ranking: '2',
    regional_ranking: '18,904',
    world_ranking: '18,904',
    hIndexTotal: '82',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '380',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '26,026',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/talha-bin-emran/11223',
    name: 'Talha Bin Emran',
    institution: 'BGC Trust University Bangladesh, Chittagong',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Pharmacy & Pharmaceutical Sciences',
    institutional_ranking: '3',
    country_ranking: '3',
    regional_ranking: '29,675',
    world_ranking: '29,675',
    hIndexTotal: '71',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '333',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '20,383',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/akhtar-hussain/44556',
    name: 'Akhtar Hussain',
    institution: 'University of Oslo',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Endocrinology & Metabolism',
    institutional_ranking: '4',
    country_ranking: '4',
    regional_ranking: '35,789',
    world_ranking: '35,789',
    hIndexTotal: '65',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '290',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '18,456',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/mahmudur-rahman/77889',
    name: 'Mahmudur Rahman',
    institution: 'International Centre for Diarrhoeal Disease Research, Dhaka',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Epidemiology',
    institutional_ranking: '5',
    country_ranking: '5',
    regional_ranking: '42,123',
    world_ranking: '42,123',
    hIndexTotal: '60',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '250',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '16,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/abdur-rahim/99100',
    name: 'Abdur Rahim',
    institution: 'Bangladesh University of Engineering and Technology',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Electrical & Electronic Engineering',
    institutional_ranking: '6',
    country_ranking: '6',
    regional_ranking: '48,567',
    world_ranking: '48,567',
    hIndexTotal: '58',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '240',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '15,432',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/asma-begum/22334',
    name: 'Asma Begum',
    institution: 'University of Dhaka',
    country: 'Bangladesh',
    field: 'Natural Sciences / Chemistry',
    institutional_ranking: '7',
    country_ranking: '7',
    regional_ranking: '55,678',
    world_ranking: '55,678',
    hIndexTotal: '55',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '220',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '14,567',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/saiful-islam/55667',
    name: 'Saiful Islam',
    institution: 'Shahjalal University of Science and Technology',
    country: 'Bangladesh',
    field: 'Natural Sciences / Physics',
    institutional_ranking: '8',
    country_ranking: '8',
    regional_ranking: '62,789',
    world_ranking: '62,789',
    hIndexTotal: '53',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '210',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '13,890',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/mahmudur-rahman/77889',
    name: 'Mahmudur Rahman',
    institution: 'International Centre for Diarrhoeal Disease Research, Dhaka',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Epidemiology',
    institutional_ranking: '5',
    country_ranking: '5',
    regional_ranking: '42,123',
    world_ranking: '42,123',
    hIndexTotal: '60',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '250',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '16,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/abdur-rahim/99100',
    name: 'Abdur Rahim',
    institution: 'Bangladesh University of Engineering and Technology',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Electrical & Electronic Engineering',
    institutional_ranking: '6',
    country_ranking: '6',
    regional_ranking: '48,567',
    world_ranking: '48,567',
    hIndexTotal: '58',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '240',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '15,432',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/asma-begum/22334',
    name: 'Asma Begum',
    institution: 'University of Dhaka',
    country: 'Bangladesh',
    field: 'Natural Sciences / Chemistry',
    institutional_ranking: '7',
    country_ranking: '7',
    regional_ranking: '55,678',
    world_ranking: '55,678',
    hIndexTotal: '55',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '220',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '14,567',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/saiful-islam/55667',
    name: 'Saiful Islam',
    institution: 'Shahjalal University of Science and Technology',
    country: 'Bangladesh',
    field: 'Natural Sciences / Physics',
    institutional_ranking: '8',
    country_ranking: '8',
    regional_ranking: '62,789',
    world_ranking: '62,789',
    hIndexTotal: '53',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '210',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '13,890',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/rahman-tarafder/88990',
    name: 'Rahman Tarafder',
    institution: 'Khulna University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Forestry',
    institutional_ranking: '9',
    country_ranking: '9',
    regional_ranking: '70,123',
    world_ranking: '70,123',
    hIndexTotal: '50',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '200',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '12,345',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/nafisa-ismail/33445',
    name: 'Nafisa Ismail',
    institution: 'North South University',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Neuroscience',
    institutional_ranking: '10',
    country_ranking: '10',
    regional_ranking: '77,456',
    world_ranking: '77,456',
    hIndexTotal: '48',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '190',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '11,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/rahman-tarafder/88990',
    name: 'Rahman Tarafder',
    institution: 'Khulna University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Forestry',
    institutional_ranking: '9',
    country_ranking: '9',
    regional_ranking: '70,123',
    world_ranking: '70,123',
    hIndexTotal: '50',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '200',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '12,345',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/nafisa-ismail/33445',
    name: 'Nafisa Ismail',
    institution: 'North South University',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Neuroscience',
    institutional_ranking: '10',
    country_ranking: '10',
    regional_ranking: '77,456',
    world_ranking: '77,456',
    hIndexTotal: '48',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '190',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '11,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/abdullah-al-mamun/55678',
    name: 'Abdullah Al Mamun',
    institution: 'Bangladesh Agricultural University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Animal Science',
    institutional_ranking: '11',
    country_ranking: '11',
    regional_ranking: '84,567',
    world_ranking: '84,567',
    hIndexTotal: '46',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '180',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '11,234',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/mahmud-hossain/66789',
    name: 'Mahmud Hossain',
    institution: 'University of Chittagong',
    country: 'Bangladesh',
    field: 'Natural Sciences / Mathematics',
    institutional_ranking: '12',
    country_ranking: '12',
    regional_ranking: '91,678',
    world_ranking: '91,678',
    hIndexTotal: '44',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '170',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '10,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/salma-sultana/77890',
    name: 'Salma Sultana',
    institution: 'Bangladesh University of Health Sciences',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Nutrition and Dietetics',
    institutional_ranking: '13',
    country_ranking: '13',
    regional_ranking: '98,789',
    world_ranking: '98,789',
    hIndexTotal: '42',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '160',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '10,345',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/aminul-islam/88991',
    name: 'Aminul Islam',
    institution: 'Jahangirnagar University',
    country: 'Bangladesh',
    field: 'Natural Sciences / Environmental Science',
    institutional_ranking: '14',
    country_ranking: '14',
    regional_ranking: '105,123',
    world_ranking: '105,123',
    hIndexTotal: '40',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '150',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,890',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/rahima-khatun/99012',
    name: 'Rahima Khatun',
    institution: 'Bangladesh University of Textiles',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Textile Engineering',
    institutional_ranking: '15',
    country_ranking: '15',
    regional_ranking: '112,345',
    world_ranking: '112,345',
    hIndexTotal: '38',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '140',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,456',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/zakir-hossain/11224',
    name: 'Zakir Hossain',
    institution: 'University of Rajshahi',
    country: 'Bangladesh',
    field: 'Natural Sciences / Botany',
    institutional_ranking: '16',
    country_ranking: '16',
    regional_ranking: '119,678',
    world_ranking: '119,678',
    hIndexTotal: '36',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '130',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,012',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/abdullah-al-mamun/55678',
    name: 'Abdullah Al Mamun',
    institution: 'Bangladesh Agricultural University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Animal Science',
    institutional_ranking: '11',
    country_ranking: '11',
    regional_ranking: '84,567',
    world_ranking: '84,567',
    hIndexTotal: '46',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '180',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '11,234',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/mahmud-hossain/66789',
    name: 'Mahmud Hossain',
    institution: 'University of Chittagong',
    country: 'Bangladesh',
    field: 'Natural Sciences / Mathematics',
    institutional_ranking: '12',
    country_ranking: '12',
    regional_ranking: '91,678',
    world_ranking: '91,678',
    hIndexTotal: '44',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '170',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '10,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/salma-sultana/77890',
    name: 'Salma Sultana',
    institution: 'Bangladesh University of Health Sciences',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Nutrition and Dietetics',
    institutional_ranking: '13',
    country_ranking: '13',
    regional_ranking: '98,789',
    world_ranking: '98,789',
    hIndexTotal: '42',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '160',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '10,345',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/aminul-islam/88991',
    name: 'Aminul Islam',
    institution: 'Jahangirnagar University',
    country: 'Bangladesh',
    field: 'Natural Sciences / Environmental Science',
    institutional_ranking: '14',
    country_ranking: '14',
    regional_ranking: '105,123',
    world_ranking: '105,123',
    hIndexTotal: '40',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '150',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,890',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/rahima-khatun/99012',
    name: 'Rahima Khatun',
    institution: 'Bangladesh University of Textiles',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Textile Engineering',
    institutional_ranking: '15',
    country_ranking: '15',
    regional_ranking: '112,345',
    world_ranking: '112,345',
    hIndexTotal: '38',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '140',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,456',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/zakir-hossain/11224',
    name: 'Zakir Hossain',
    institution: 'University of Rajshahi',
    country: 'Bangladesh',
    field: 'Natural Sciences / Botany',
    institutional_ranking: '16',
    country_ranking: '16',
    regional_ranking: '119,678',
    world_ranking: '119,678',
    hIndexTotal: '36',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '130',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,012',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/munira-sultana/22335',
    name: 'Munira Sultana',
    institution: 'Bangladesh Open University',
    country: 'Bangladesh',
    field: 'Social Sciences / Education',
    institutional_ranking: '17',
    country_ranking: '17',
    regional_ranking: '126,789',
    world_ranking: '126,789',
    hIndexTotal: '34',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '120',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '8,567',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/abdul-kader/33446',
    name: 'Abdul Kader',
    institution: 'Islamic University of Technology',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Mechanical Engineering',
    institutional_ranking: '18',
    country_ranking: '18',
    regional_ranking: '133,123',
    world_ranking: '133,123',
    hIndexTotal: '32',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '110',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '8,123',
    citationsLast6Years: 'N/A',
  },
  {
    profile:
      'https://www.adscientificindex.com/scientist/abdullah-al-mamun/55678',
    name: 'Abdullah Al Mamun',
    institution: 'Bangladesh Agricultural University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Animal Science',
    institutional_ranking: '11',
    country_ranking: '11',
    regional_ranking: '84,567',
    world_ranking: '84,567',
    hIndexTotal: '46',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '180',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '11,234',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/mahmud-hossain/66789',
    name: 'Mahmud Hossain',
    institution: 'University of Chittagong',
    country: 'Bangladesh',
    field: 'Natural Sciences / Mathematics',
    institutional_ranking: '12',
    country_ranking: '12',
    regional_ranking: '91,678',
    world_ranking: '91,678',
    hIndexTotal: '44',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '170',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '10,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/salma-sultana/77890',
    name: 'Salma Sultana',
    institution: 'Bangladesh University of Health Sciences',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Nutrition and Dietetics',
    institutional_ranking: '13',
    country_ranking: '13',
    regional_ranking: '98,789',
    world_ranking: '98,789',
    hIndexTotal: '42',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '160',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '10,345',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/aminul-islam/88991',
    name: 'Aminul Islam',
    institution: 'Jahangirnagar University',
    country: 'Bangladesh',
    field: 'Natural Sciences / Environmental Science',
    institutional_ranking: '14',
    country_ranking: '14',
    regional_ranking: '105,123',
    world_ranking: '105,123',
    hIndexTotal: '40',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '150',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,890',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/rahima-khatun/99012',
    name: 'Rahima Khatun',
    institution: 'Bangladesh University of Textiles',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Textile Engineering',
    institutional_ranking: '15',
    country_ranking: '15',
    regional_ranking: '112,345',
    world_ranking: '112,345',
    hIndexTotal: '38',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '140',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,456',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/zakir-hossain/11224',
    name: 'Zakir Hossain',
    institution: 'University of Rajshahi',
    country: 'Bangladesh',
    field: 'Natural Sciences / Botany',
    institutional_ranking: '16',
    country_ranking: '16',
    regional_ranking: '119,678',
    world_ranking: '119,678',
    hIndexTotal: '36',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '130',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '9,012',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/munira-sultana/22335',
    name: 'Munira Sultana',
    institution: 'Bangladesh Open University',
    country: 'Bangladesh',
    field: 'Social Sciences / Education',
    institutional_ranking: '17',
    country_ranking: '17',
    regional_ranking: '126,789',
    world_ranking: '126,789',
    hIndexTotal: '34',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '120',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '8,567',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/abdul-kader/33446',
    name: 'Abdul Kader',
    institution: 'Islamic University of Technology',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Mechanical Engineering',
    institutional_ranking: '18',
    country_ranking: '18',
    regional_ranking: '133,123',
    world_ranking: '133,123',
    hIndexTotal: '32',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '110',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '8,123',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/rahman-habib/44557',
    name: 'Rahman Habib',
    institution: 'Bangladesh University of Professionals',
    country: 'Bangladesh',
    field: 'Social Sciences / Sociology',
    institutional_ranking: '19',
    country_ranking: '19',
    regional_ranking: '140,456',
    world_ranking: '140,456',
    hIndexTotal: '30',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '100',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '7,678',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/afroza-begum/55668',
    name: 'Afroza Begum',
    institution: 'Khulna University',
    country: 'Bangladesh',
    field: 'Natural Sciences / Chemistry',
    institutional_ranking: '20',
    country_ranking: '20',
    regional_ranking: '147,789',
    world_ranking: '147,789',
    hIndexTotal: '28',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '90',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '7,234',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/mahfuzul-haque/66779',
    name: 'Mahfuzul Haque',
    institution: 'Shahjalal University of Science and Technology',
    country: 'Bangladesh',
    field: 'Engineering & Technology / Computer Science',
    institutional_ranking: '21',
    country_ranking: '21',
    regional_ranking: '154,123',
    world_ranking: '154,123',
    hIndexTotal: '26',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '80',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '6,789',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/nahid-sultana/77880',
    name: 'Nahid Sultana',
    institution: 'Noakhali Science and Technology University',
    country: 'Bangladesh',
    field: 'Medical and Health Sciences / Public Health',
    institutional_ranking: '22',
    country_ranking: '22',
    regional_ranking: '161,456',
    world_ranking: '161,456',
    hIndexTotal: '24',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '70',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '6,345',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/abdul-karim/88981',
    name: 'Abdul Karim',
    institution: 'Patuakhali Science and Technology University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Fisheries',
    institutional_ranking: '23',
    country_ranking: '23',
    regional_ranking: '168,789',
    world_ranking: '168,789',
    hIndexTotal: '22',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '60',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '5,901',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/rahima-begum/99002',
    name: 'Rahima Begum',
    institution: 'Jessore University of Science and Technology',
    country: 'Bangladesh',
    field: 'Natural Sciences / Physics',
    institutional_ranking: '24',
    country_ranking: '24',
    regional_ranking: '176,123',
    world_ranking: '176,123',
    hIndexTotal: '20',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '50',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '5,456',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/zakir-hossain/11214',
    name: 'Zakir Hossain',
    institution: 'Bangabandhu Sheikh Mujibur Rahman Agricultural University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Soil Science',
    institutional_ranking: '25',
    country_ranking: '25',
    regional_ranking: '183,456',
    world_ranking: '183,456',
    hIndexTotal: '18',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '40',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '5,012',
    citationsLast6Years: 'N/A',
  },
  {
    profile: 'https://www.adscientificindex.com/scientist/munira-sultana/22325',
    name: 'Munira Sultana',
    institution: 'Chittagong Veterinary and Animal Sciences University',
    country: 'Bangladesh',
    field: 'Agricultural Sciences / Veterinary Science',
    institutional_ranking: '26',
    country_ranking: '26',
    regional_ranking: '190,789',
    world_ranking: '190,789',
    hIndexTotal: '16',
    hIndexLast6Years: 'N/A',
    i10IndexTotal: '30',
    i10IndexLast6Years: 'N/A',
    citationsTotal: '4,567',
    citationsLast6Years: 'N/A',
  },
];

export const socials = [
  {
    id: '0',
    title: 'Discord',
    iconUrl: discordBlack,
    url: '#',
  },
  {
    id: '1',
    title: 'Twitter',
    iconUrl: twitter,
    url: '#',
  },
  {
    id: '2',
    title: 'Instagram',
    iconUrl: instagram,
    url: '#',
  },
  {
    id: '3',
    title: 'Telegram',
    iconUrl: telegram,
    url: '#',
  },
  {
    id: '4',
    title: 'Facebook',
    iconUrl: facebook,
    url: '#',
  },
];
